_wandb:
    value:
        cli_version: 0.18.0
        m: []
        python_version: 3.11.8
        t:
            "1":
                - 1
                - 5
                - 53
                - 55
                - 77
            "2":
                - 1
                - 5
                - 53
                - 55
                - 77
            "3":
                - 16
                - 23
                - 55
            "4": 3.11.8
            "5": 0.18.0
            "8":
                - 5
            "12": 0.18.0
            "13": linux-x86_64
dataset:
    value: Cora
epochs:
    value: 20
learning_rate:
    value: 0.01
model_type:
    value: KAN-GPS
momentum:
    value: 0.9
num_classes:
    value: 7
num_epochs:
    value: 20
num_features:
    value: 1433
optimizer:
    value: SGD
task:
    value: node
weight_decay:
    value: 0.0005
